# Site settings
title: 
email: julio.m.henriquez@gmail.com
description: 
baseurl: 
url:  
github_username:  jhenriquez
exclude: ['components', 'node_modules', 'Gruntfile.js', 'package.json', 'bower.json']
# Build settings
markdown: kramdown
